services:
  veldafrica-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veldafrica-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:80"
    networks:
      - veldafrica-network

networks:
  veldafrica-network:
    driver: bridge
